dist: trusty
sudo: false
language: cpp
jdk: oraclejdk8

matrix:
  include:
   # Linux GCC Builds
    - os: linux
      compiler: gcc
      addons: &gcc7
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['g++-7', 'gcc-7','libgmp-dev', 'flex', 'byacc', 'libfl-dev','libxml++2.6-2']
      env: GCCVER='7' CXX_COMPILER='g++-7' C_COMPILER='gcc-7'

    # 4/ OSX GCC Builds
    - os: osx
      osx_image: xcode8.3
#      compiler: gcc
#      env: GCCVER='8' CXX_COMPILER='g++-8' C_COMPILER='gcc-8'

before_script:
## OSX
  - cd ${TRAVIS_BUILD_DIR} 
  - export CXX=${CXX_COMPILER}
  - export CC=${C_COMPILER}
 #  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then rm /usr/local/include/c++         ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install gmp boost flex byacc ant graphviz libxml++ autoconf automake libtool ; fi  
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then export TARGETBRANCH=osx ; fi
  # linux only
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then export AR=gcc-ar-${GCCVER} ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then export RANLIB=gcc-ranlib-${GCCVER} ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then export NM=gcc-nm-${GCCVER} ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then export TARGETBRANCH=gh-pages ; fi

# build
script :
  - ./tag.sh
  - ./build_GreatSPN.sh
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then mv website/greatspn_linux.tar.gz website/greatspn_osx.tar.gz ; fi
  - ls -lah website/

cache:
  directories:
    - '${TRAVIS_BUILD_DIR}/usr/'

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  local_dir: website/
  target_branch: $TARGETBRANCH
  on:
    branch: master
