language: java

matrix:
  include:
   # Linux GCC Builds
    - os: linux
      compiler: gcc
      addons: &gcc9
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['g++-9', 'gcc-9','libxml++2.6-2v5', 'libboost-all-dev']
      env: GCCVER='9' CXX_COMPILER='g++-9' C_COMPILER='gcc-9'

    # 4/ OSX GCC Builds
    - os: osx
      osx_image: xcode11.2
      compiler: gcc
      addons:
        homebrew:
          packages:
            - gcc
            - make
            - ant
            - graphviz
            - libxml++
      env: GCCVER='9' CXX_COMPILER='g++-9' C_COMPILER='gcc-9'

before_script:
## OSX
  - cd ${TRAVIS_BUILD_DIR} 
  - export CXX=${CXX_COMPILER}
  - export CC=${C_COMPILER}
  # - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then rm /usr/local/include/c++         ; fi
  # - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install gcc make ant graphviz libxml++ ; fi  
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then export TARGETBRANCH=osx ; fi
  # linux only
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then export AR=gcc-ar-${GCCVER} ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then export RANLIB=gcc-ranlib-${GCCVER} ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then export NM=gcc-nm-${GCCVER} ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then export TARGETBRANCH=gh-pages ; fi

# build
script :
  - aptitude search boost
  - ./tag.sh
  - ./build_GreatSPN.sh
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then mv website/greatspn_linux.tar.gz website/greatspn_osx.tar.gz ; fi
  - ls -lah website/

cache:
  directories:
    - '${TRAVIS_BUILD_DIR}/usr/'

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  local_dir: website/
  target_branch: $TARGETBRANCH
  on:
    branch: master
