build:
  verbosity: minimal

clone_depth: 30

build_script :
 - '%BASH_PATH% -lc "cd $APPVEYOR_BUILD_FOLDER; ./build_greatspn.sh && mv website/greatspn_linux.tar.gz website/greatspn_windows.tar.gz"'
 - DIR

 
environment :
 MSYSTEM: MINGW64 
 BASH_PATH: C:\msys64\usr\bin\bash

 
artifacts:
  - path: website/greatspn_windows.tar.gz
    name: greatspn_windows.tar.gz


      
